/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : convert-certificate
 #	author : miyako
 #	2017/03/15
 #
 # --------------------------------------------------------------------------------*/

#include "openssl/ssl.h"
#include "openssl/bio.h"
#include "openssl/evp.h"
#include "openssl/buffer.h"
#include "openssl/hmac.h"
#include "openssl/pkcs12.h"
#include "openssl/err.h"
#include "openssl/sha.h"

// --- Convert
void P12_TO_PEM(sLONG_PTR *pResult, PackagePtr pParams);
